CREATE TABLE oauth_infos (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    access_token TEXT NOT NULL DEFAULT '',
    account_id TEXT NOT NULL DEFAULT '',
    disabled BOOLEAN NOT NULL DEFAULT FALSE,
    email TEXT NOT NULL DEFAULT '',
    expired TIMESTAMPTZ,
    id_token TEXT NOT NULL DEFAULT '',
    last_refresh TIMESTAMPTZ,
    refresh_token TEXT NOT NULL DEFAULT '',
    type TEXT NOT NULL DEFAULT 'codex',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
