// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/upstream.proto

package upstream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpstreamService_ExchangeCode_FullMethodName = "/upstream.UpstreamService/ExchangeCode"
	UpstreamService_RefreshToken_FullMethodName = "/upstream.UpstreamService/RefreshToken"
)

// UpstreamServiceClient is the client API for UpstreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpstreamServiceClient interface {
	ExchangeCode(ctx context.Context, in *ExchangeCodeRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	// Reserved for a later phase; currently returns UNIMPLEMENTED.
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
}

type upstreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpstreamServiceClient(cc grpc.ClientConnInterface) UpstreamServiceClient {
	return &upstreamServiceClient{cc}
}

func (c *upstreamServiceClient) ExchangeCode(ctx context.Context, in *ExchangeCodeRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, UpstreamService_ExchangeCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upstreamServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, UpstreamService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpstreamServiceServer is the server API for UpstreamService service.
// All implementations must embed UnimplementedUpstreamServiceServer
// for forward compatibility.
type UpstreamServiceServer interface {
	ExchangeCode(context.Context, *ExchangeCodeRequest) (*TokenResponse, error)
	// Reserved for a later phase; currently returns UNIMPLEMENTED.
	RefreshToken(context.Context, *RefreshTokenRequest) (*TokenResponse, error)
	mustEmbedUnimplementedUpstreamServiceServer()
}

// UnimplementedUpstreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpstreamServiceServer struct{}

func (UnimplementedUpstreamServiceServer) ExchangeCode(context.Context, *ExchangeCodeRequest) (*TokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeCode not implemented")
}
func (UnimplementedUpstreamServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*TokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedUpstreamServiceServer) mustEmbedUnimplementedUpstreamServiceServer() {}
func (UnimplementedUpstreamServiceServer) testEmbeddedByValue()                         {}

// UnsafeUpstreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpstreamServiceServer will
// result in compilation errors.
type UnsafeUpstreamServiceServer interface {
	mustEmbedUnimplementedUpstreamServiceServer()
}

func RegisterUpstreamServiceServer(s grpc.ServiceRegistrar, srv UpstreamServiceServer) {
	// If the following call panics, it indicates UnimplementedUpstreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpstreamService_ServiceDesc, srv)
}

func _UpstreamService_ExchangeCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpstreamServiceServer).ExchangeCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpstreamService_ExchangeCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpstreamServiceServer).ExchangeCode(ctx, req.(*ExchangeCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpstreamService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpstreamServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpstreamService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpstreamServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpstreamService_ServiceDesc is the grpc.ServiceDesc for UpstreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpstreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "upstream.UpstreamService",
	HandlerType: (*UpstreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExchangeCode",
			Handler:    _UpstreamService_ExchangeCode_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _UpstreamService_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/upstream.proto",
}
