// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/upstream.proto

package upstream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExchangeCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// PKCE 校验用，对应 oauth2.VerifierOption(flow.Verifier)
	CodeVerifier string `protobuf:"bytes,2,opt,name=code_verifier,json=codeVerifier,proto3" json:"code_verifier,omitempty"`
	Provider     string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	// Empty preserves the existing browser flow. Set by the API, not browser input.
	FlowType      string `protobuf:"bytes,4,opt,name=flow_type,json=flowType,proto3" json:"flow_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeCodeRequest) Reset() {
	*x = ExchangeCodeRequest{}
	mi := &file_proto_upstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCodeRequest) ProtoMessage() {}

func (x *ExchangeCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCodeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_upstream_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExchangeCodeRequest) GetCodeVerifier() string {
	if x != nil {
		return x.CodeVerifier
	}
	return ""
}

func (x *ExchangeCodeRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ExchangeCodeRequest) GetFlowType() string {
	if x != nil {
		return x.FlowType
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_proto_upstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_upstream_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IdToken       string                 `protobuf:"bytes,5,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_proto_upstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_upstream_proto_rawDescGZIP(), []int{2}
}

func (x *TokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TokenResponse) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type ProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must match a configured issuer, not an arbitrary URL to fetch.
	Issuer        string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderRequest) Reset() {
	*x = ProviderRequest{}
	mi := &file_proto_upstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderRequest) ProtoMessage() {}

func (x *ProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderRequest.ProtoReflect.Descriptor instead.
func (*ProviderRequest) Descriptor() ([]byte, []int) {
	return file_proto_upstream_proto_rawDescGZIP(), []int{3}
}

func (x *ProviderRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

type DeviceFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceFlowRequest) Reset() {
	*x = DeviceFlowRequest{}
	mi := &file_proto_upstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceFlowRequest) ProtoMessage() {}

func (x *DeviceFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceFlowRequest.ProtoReflect.Descriptor instead.
func (*DeviceFlowRequest) Descriptor() ([]byte, []int) {
	return file_proto_upstream_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceFlowRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type DeviceFlowResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceAuthId    string                 `protobuf:"bytes,1,opt,name=device_auth_id,json=deviceAuthId,proto3" json:"device_auth_id,omitempty"`
	UserCode        string                 `protobuf:"bytes,2,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	IntervalSeconds uint32                 `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	VerificationUrl string                 `protobuf:"bytes,4,opt,name=verification_url,json=verificationUrl,proto3" json:"verification_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeviceFlowResponse) Reset() {
	*x = DeviceFlowResponse{}
	mi := &file_proto_upstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceFlowResponse) ProtoMessage() {}

func (x *DeviceFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceFlowResponse.ProtoReflect.Descriptor instead.
func (*DeviceFlowResponse) Descriptor() ([]byte, []int) {
	return file_proto_upstream_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceFlowResponse) GetDeviceAuthId() string {
	if x != nil {
		return x.DeviceAuthId
	}
	return ""
}

func (x *DeviceFlowResponse) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *DeviceFlowResponse) GetIntervalSeconds() uint32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *DeviceFlowResponse) GetVerificationUrl() string {
	if x != nil {
		return x.VerificationUrl
	}
	return ""
}

type PollDeviceFlowRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Provider     string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	DeviceAuthId string                 `protobuf:"bytes,2,opt,name=device_auth_id,json=deviceAuthId,proto3" json:"device_auth_id,omitempty"`
	UserCode     string                 `protobuf:"bytes,3,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	// Positive interval returned by GetDeviceFlowCode; maximum 900 seconds.
	IntervalSeconds uint32 `protobuf:"varint,4,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PollDeviceFlowRequest) Reset() {
	*x = PollDeviceFlowRequest{}
	mi := &file_proto_upstream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollDeviceFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollDeviceFlowRequest) ProtoMessage() {}

func (x *PollDeviceFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upstream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollDeviceFlowRequest.ProtoReflect.Descriptor instead.
func (*PollDeviceFlowRequest) Descriptor() ([]byte, []int) {
	return file_proto_upstream_proto_rawDescGZIP(), []int{6}
}

func (x *PollDeviceFlowRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PollDeviceFlowRequest) GetDeviceAuthId() string {
	if x != nil {
		return x.DeviceAuthId
	}
	return ""
}

func (x *PollDeviceFlowRequest) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *PollDeviceFlowRequest) GetIntervalSeconds() uint32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

// Internal credentials: must not be returned to the browser.
type DeviceAuthorizationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationCode string                 `protobuf:"bytes,1,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	CodeVerifier      string                 `protobuf:"bytes,2,opt,name=code_verifier,json=codeVerifier,proto3" json:"code_verifier,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeviceAuthorizationResponse) Reset() {
	*x = DeviceAuthorizationResponse{}
	mi := &file_proto_upstream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAuthorizationResponse) ProtoMessage() {}

func (x *DeviceAuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upstream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAuthorizationResponse.ProtoReflect.Descriptor instead.
func (*DeviceAuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_proto_upstream_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceAuthorizationResponse) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

func (x *DeviceAuthorizationResponse) GetCodeVerifier() string {
	if x != nil {
		return x.CodeVerifier
	}
	return ""
}

type ProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	AuthURL       string                 `protobuf:"bytes,2,opt,name=authURL,proto3" json:"authURL,omitempty"`
	TokenURL      string                 `protobuf:"bytes,3,opt,name=tokenURL,proto3" json:"tokenURL,omitempty"`
	DeviceAuthURL string                 `protobuf:"bytes,4,opt,name=deviceAuthURL,proto3" json:"deviceAuthURL,omitempty"`
	UserInfoURL   string                 `protobuf:"bytes,5,opt,name=userInfoURL,proto3" json:"userInfoURL,omitempty"`
	JwksURL       string                 `protobuf:"bytes,6,opt,name=jwksURL,proto3" json:"jwksURL,omitempty"`
	Algorithms    []string               `protobuf:"bytes,7,rep,name=algorithms,proto3" json:"algorithms,omitempty"`
	RawClaims     []byte                 `protobuf:"bytes,8,opt,name=rawClaims,proto3" json:"rawClaims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderResponse) Reset() {
	*x = ProviderResponse{}
	mi := &file_proto_upstream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderResponse) ProtoMessage() {}

func (x *ProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upstream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderResponse.ProtoReflect.Descriptor instead.
func (*ProviderResponse) Descriptor() ([]byte, []int) {
	return file_proto_upstream_proto_rawDescGZIP(), []int{8}
}

func (x *ProviderResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *ProviderResponse) GetAuthURL() string {
	if x != nil {
		return x.AuthURL
	}
	return ""
}

func (x *ProviderResponse) GetTokenURL() string {
	if x != nil {
		return x.TokenURL
	}
	return ""
}

func (x *ProviderResponse) GetDeviceAuthURL() string {
	if x != nil {
		return x.DeviceAuthURL
	}
	return ""
}

func (x *ProviderResponse) GetUserInfoURL() string {
	if x != nil {
		return x.UserInfoURL
	}
	return ""
}

func (x *ProviderResponse) GetJwksURL() string {
	if x != nil {
		return x.JwksURL
	}
	return ""
}

func (x *ProviderResponse) GetAlgorithms() []string {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *ProviderResponse) GetRawClaims() []byte {
	if x != nil {
		return x.RawClaims
	}
	return nil
}

type VerifyRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Rawidtoken string                 `protobuf:"bytes,1,opt,name=rawidtoken,proto3" json:"rawidtoken,omitempty"`
	// Configured provider key, e.g. "oai"; selects issuer and client ID checks.
	Provider      string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_proto_upstream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upstream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_upstream_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyRequest) GetRawidtoken() string {
	if x != nil {
		return x.Rawidtoken
	}
	return ""
}

func (x *VerifyRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

// Returned only after signature, issuer, audience and expiry validation.
// The API must still compare nonce with its stored login flow before saving.
type VerifyResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Issuer    string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject   string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Audience  []string               `protobuf:"bytes,3,rep,name=audience,proto3" json:"audience,omitempty"`
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IssuedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	Nonce     string                 `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Verified JSON claims, including provider-specific account and email fields.
	ClaimsJson    []byte `protobuf:"bytes,7,opt,name=claims_json,json=claimsJson,proto3" json:"claims_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_proto_upstream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upstream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_upstream_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *VerifyResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *VerifyResponse) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *VerifyResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *VerifyResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *VerifyResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *VerifyResponse) GetClaimsJson() []byte {
	if x != nil {
		return x.ClaimsJson
	}
	return nil
}

var File_proto_upstream_proto protoreflect.FileDescriptor

const file_proto_upstream_proto_rawDesc = "" +
	"\n" +
	"\x14proto/upstream.proto\x12\bupstream\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n" +
	"\x13ExchangeCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rcode_verifier\x18\x02 \x01(\tR\fcodeVerifier\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1b\n" +
	"\tflow_type\x18\x04 \x01(\tR\bflowType\"V\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\xcc\x01\n" +
	"\rTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x19\n" +
	"\bid_token\x18\x05 \x01(\tR\aidToken\")\n" +
	"\x0fProviderRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\"/\n" +
	"\x11DeviceFlowRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"\xad\x01\n" +
	"\x12DeviceFlowResponse\x12$\n" +
	"\x0edevice_auth_id\x18\x01 \x01(\tR\fdeviceAuthId\x12\x1b\n" +
	"\tuser_code\x18\x02 \x01(\tR\buserCode\x12)\n" +
	"\x10interval_seconds\x18\x03 \x01(\rR\x0fintervalSeconds\x12)\n" +
	"\x10verification_url\x18\x04 \x01(\tR\x0fverificationUrl\"\xa1\x01\n" +
	"\x15PollDeviceFlowRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12$\n" +
	"\x0edevice_auth_id\x18\x02 \x01(\tR\fdeviceAuthId\x12\x1b\n" +
	"\tuser_code\x18\x03 \x01(\tR\buserCode\x12)\n" +
	"\x10interval_seconds\x18\x04 \x01(\rR\x0fintervalSeconds\"q\n" +
	"\x1bDeviceAuthorizationResponse\x12-\n" +
	"\x12authorization_code\x18\x01 \x01(\tR\x11authorizationCode\x12#\n" +
	"\rcode_verifier\x18\x02 \x01(\tR\fcodeVerifier\"\x80\x02\n" +
	"\x10ProviderResponse\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x18\n" +
	"\aauthURL\x18\x02 \x01(\tR\aauthURL\x12\x1a\n" +
	"\btokenURL\x18\x03 \x01(\tR\btokenURL\x12$\n" +
	"\rdeviceAuthURL\x18\x04 \x01(\tR\rdeviceAuthURL\x12 \n" +
	"\vuserInfoURL\x18\x05 \x01(\tR\vuserInfoURL\x12\x18\n" +
	"\ajwksURL\x18\x06 \x01(\tR\ajwksURL\x12\x1e\n" +
	"\n" +
	"algorithms\x18\a \x03(\tR\n" +
	"algorithms\x12\x1c\n" +
	"\trawClaims\x18\b \x01(\fR\trawClaims\"K\n" +
	"\rVerifyRequest\x12\x1e\n" +
	"\n" +
	"rawidtoken\x18\x01 \x01(\tR\n" +
	"rawidtoken\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\x89\x02\n" +
	"\x0eVerifyResponse\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1a\n" +
	"\baudience\x18\x03 \x03(\tR\baudience\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\tR\x05nonce\x12\x1f\n" +
	"\vclaims_json\x18\a \x01(\fR\n" +
	"claimsJson2\xd0\x03\n" +
	"\x0fUpstreamService\x12N\n" +
	"\x11GetDeviceFlowCode\x12\x1b.upstream.DeviceFlowRequest\x1a\x1c.upstream.DeviceFlowResponse\x12X\n" +
	"\x0ePollDeviceFlow\x12\x1f.upstream.PollDeviceFlowRequest\x1a%.upstream.DeviceAuthorizationResponse\x12F\n" +
	"\fExchangeCode\x12\x1d.upstream.ExchangeCodeRequest\x1a\x17.upstream.TokenResponse\x12F\n" +
	"\fRefreshToken\x12\x1d.upstream.RefreshTokenRequest\x1a\x17.upstream.TokenResponse\x12D\n" +
	"\vGetProvider\x12\x19.upstream.ProviderRequest\x1a\x1a.upstream.ProviderResponse\x12=\n" +
	"\bVerifier\x12\x17.upstream.VerifyRequest\x1a\x18.upstream.VerifyResponseB\x1dZ\x1berent/internal/rpc/upstreamb\x06proto3"

var (
	file_proto_upstream_proto_rawDescOnce sync.Once
	file_proto_upstream_proto_rawDescData []byte
)

func file_proto_upstream_proto_rawDescGZIP() []byte {
	file_proto_upstream_proto_rawDescOnce.Do(func() {
		file_proto_upstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_upstream_proto_rawDesc), len(file_proto_upstream_proto_rawDesc)))
	})
	return file_proto_upstream_proto_rawDescData
}

var file_proto_upstream_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_upstream_proto_goTypes = []any{
	(*ExchangeCodeRequest)(nil),         // 0: upstream.ExchangeCodeRequest
	(*RefreshTokenRequest)(nil),         // 1: upstream.RefreshTokenRequest
	(*TokenResponse)(nil),               // 2: upstream.TokenResponse
	(*ProviderRequest)(nil),             // 3: upstream.ProviderRequest
	(*DeviceFlowRequest)(nil),           // 4: upstream.DeviceFlowRequest
	(*DeviceFlowResponse)(nil),          // 5: upstream.DeviceFlowResponse
	(*PollDeviceFlowRequest)(nil),       // 6: upstream.PollDeviceFlowRequest
	(*DeviceAuthorizationResponse)(nil), // 7: upstream.DeviceAuthorizationResponse
	(*ProviderResponse)(nil),            // 8: upstream.ProviderResponse
	(*VerifyRequest)(nil),               // 9: upstream.VerifyRequest
	(*VerifyResponse)(nil),              // 10: upstream.VerifyResponse
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
}
var file_proto_upstream_proto_depIdxs = []int32{
	11, // 0: upstream.TokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	11, // 1: upstream.VerifyResponse.expires_at:type_name -> google.protobuf.Timestamp
	11, // 2: upstream.VerifyResponse.issued_at:type_name -> google.protobuf.Timestamp
	4,  // 3: upstream.UpstreamService.GetDeviceFlowCode:input_type -> upstream.DeviceFlowRequest
	6,  // 4: upstream.UpstreamService.PollDeviceFlow:input_type -> upstream.PollDeviceFlowRequest
	0,  // 5: upstream.UpstreamService.ExchangeCode:input_type -> upstream.ExchangeCodeRequest
	1,  // 6: upstream.UpstreamService.RefreshToken:input_type -> upstream.RefreshTokenRequest
	3,  // 7: upstream.UpstreamService.GetProvider:input_type -> upstream.ProviderRequest
	9,  // 8: upstream.UpstreamService.Verifier:input_type -> upstream.VerifyRequest
	5,  // 9: upstream.UpstreamService.GetDeviceFlowCode:output_type -> upstream.DeviceFlowResponse
	7,  // 10: upstream.UpstreamService.PollDeviceFlow:output_type -> upstream.DeviceAuthorizationResponse
	2,  // 11: upstream.UpstreamService.ExchangeCode:output_type -> upstream.TokenResponse
	2,  // 12: upstream.UpstreamService.RefreshToken:output_type -> upstream.TokenResponse
	8,  // 13: upstream.UpstreamService.GetProvider:output_type -> upstream.ProviderResponse
	10, // 14: upstream.UpstreamService.Verifier:output_type -> upstream.VerifyResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_upstream_proto_init() }
func file_proto_upstream_proto_init() {
	if File_proto_upstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_upstream_proto_rawDesc), len(file_proto_upstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_upstream_proto_goTypes,
		DependencyIndexes: file_proto_upstream_proto_depIdxs,
		MessageInfos:      file_proto_upstream_proto_msgTypes,
	}.Build()
	File_proto_upstream_proto = out.File
	file_proto_upstream_proto_goTypes = nil
	file_proto_upstream_proto_depIdxs = nil
}
